version: '3.2'
services:
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    #restart: unless-stopped
    networks:
    - default
    volumes:
    - grafana-storage:/var/lib/grafana
    ports:
    - '3000:3000'
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
    - 9090:9090
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    networks:
    - default
    - kafka_docker_net
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    - prometheus-data:/prometheus
    depends_on:
    - cadvisor
  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    command:
    - '--path.rootfs=/host'
    network_mode: host
    pid: host
    restart: unless-stopped
    volumes:
    - '/:/host:ro,rslave'
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
    - 8080:8080
    networks:
    - default
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
volumes:
  grafana-storage:
  prometheus-data:
networks:
  default:
  kafka_docker_net:
    external: true
