name: Continuous Integration
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  codequality:
    uses: ./.github/workflows/code_quality.yml

  testing:
    needs: codequality
    uses: ./.github/workflows/test.yml

  # docs:
  #   needs: codequality
  #   uses: ./.github/workflows/docs.yml