name: Generate Project Documentation

on:
  workflow_call:

concurrency:
  group: "pages"
  cancel-in-progress: false

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  docs:
    runs-on: ubuntu-latest
    name: Generate Documentation
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4
        with:
          fetch-depth: '1'

      - name: Setup Python environment
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Build docs
        run: |
          sphinx-build -M html ./ ./_docs

      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: './docs/pages/html'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4